name: Publish_0
on:
  workflow_run:
    workflows: [ Publish ]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        version: ["1.0.0-client", "1.0.0-rc1-client", "1.0.0-rc2-3-client", "1.0.0-rc2-3-server", "1.0.0-server", "1.0.1-server", "1.1-client", "1.1-server", "1.10", "1.10-pre1", "1.10-pre2", "1.10.1", "1.10.2", "1.11", "1.11-pre1", "1.11.1", "1.11.2", "1.12", "1.12-pre1", "1.12-pre2", "1.12-pre3-1409", "1.12-pre4", "1.12-pre5", "1.12-pre6", "1.12-pre7", "1.12.1", "1.12.1-pre1", "1.12.2", "1.12.2-pre1", "1.12.2-pre2", "1.13", "1.13-pre1", "1.13-pre10", "1.13-pre2", "1.13-pre3", "1.13-pre4", "1.13-pre5", "1.13-pre6", "1.13-pre7", "1.13-pre8", "1.13-pre9", "1.13.1", "1.13.1-pre1", "1.13.1-pre2", "1.13.2", "1.13.2-pre1", "1.13.2-pre2", "1.2-client", "1.2-server", "1.2.1-client", "1.2.1-server", "1.2.2-client", "1.2.2-server", "1.2.3-client", "1.2.3-server", "1.2.4-client", "1.2.4-server", "1.2.5-client", "1.2.5-server", "1.3-pre-07261249", "1.3.1", "1.3.2", "1.4-pre", "1.4.1-pre-10231538", "1.4.2", "1.4.3-pre", "1.4.4", "1.4.5", "1.4.6", "1.4.7", "1.5", "1.5.1", "1.5.2", "1.6-pre-06251516", "1.6.1", "1.6.2-091847", "1.6.3-pre-171231", "1.6.4", "1.7-pre", "1.7.1-pre", "1.7.10", "1.7.10-pre1", "1.7.10-pre2", "1.7.10-pre3", "1.7.10-pre4", "1.7.2", "1.7.3-pre", "1.7.4", "1.7.5", "1.7.6", "1.7.6-pre1", "1.7.6-pre2", "1.7.7-101331", "1.7.8", "1.7.9", "1.8", "1.8-pre1", "1.8-pre2", "1.8-pre3", "1.8.1", "1.8.1-pre1", "1.8.1-pre2", "1.8.1-pre3", "1.8.1-pre4", "1.8.1-pre5", "1.8.2", "1.8.2-pre1", "1.8.2-pre2", "1.8.2-pre3", "1.8.2-pre4", "1.8.2-pre5", "1.8.2-pre6", "1.8.2-pre7", "1.8.3", "1.8.4", "1.8.5", "1.8.6", "1.8.7", "1.8.8", "1.8.9", "1.9", "1.9-pre1", "1.9-pre2", "1.9-pre3", "1.9-pre4", "1.9.1", "1.9.1-pre1", "1.9.1-pre2", "1.9.1-pre3", "1.9.2", "1.9.3", "1.9.3-pre1", "1.9.3-pre2", "1.9.3-pre3", "1.9.4", "11w47a-client", "11w47a-server", "11w48a-client", "11w48a-server", "11w49a-client", "11w49a-server", "11w50a-client", "11w50a-server", "12w01a-client", "12w01a-server", "12w03a-client", "12w03a-server", "12w04a-client", "12w04a-server", "12w05a-1442-client", "12w05a-1442-server", "12w05b-client", "12w05b-server", "12w06a-client", "12w06a-server", "12w07a-client", "12w07a-server", "12w07b-client", "12w07b-server", "12w08a-client", "12w08a-server", "12w15a-client", "12w15a-server", "12w16a-client", "12w16a-server", "12w17a-client", "12w17a-server", "12w18a-client", "12w18a-server", "12w19a-client", "12w19a-server", "12w21a-client", "12w21a-server", "12w21b-client", "12w21b-server", "12w22a-client", "12w22a-server", "12w23a-client", "12w23a-server", "12w23b-client", "12w23b-server", "12w24a-client", "12w24a-server", "12w25a-client", "12w25a-server", "12w26a-client", "12w26a-server", "12w27a-client", "12w27a-server", "12w30a-client", "12w30a-server", "12w30b-client", "12w30b-server", "12w30c-client", "12w30c-server", "12w30d-client", "12w30d-server", "12w30e-client", "12w30e-server", "12w32a", "12w34a", "12w34b", "12w36a", "12w37a", "12w38a", "12w38b", "12w39a", "12w39b", "12w40a", "12w40b", "12w41a", "12w41b", "12w42a", "12w42b", "12w49a", "12w50a", "12w50b", "13w01a", "13w01b", "13w02a", "13w02b", "13w03a-1647", "13w04a", "13w05a-1538", "13w05b", "13w06a-1636", "13w07a", "13w09a", "13w09b", "13w09c"]

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: run publish script
        run: python3 feather.py publish ${{ matrix.version }}
        env:
          MAVEN_URL: ${{ secrets.NEW_MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.NEW_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.NEW_MAVEN_PASSWORD }}